---
- hosts: all
  user: root
  tasks:
    - name: install git
      yum:
        name: git
        state: present
    - name: install maven
      yum:
        name: maven
        state: present
    - name: download tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.79/bin/apache-tomcat-9.0.79.tar.gz
        dest: /opt
    - name: extract
      unarchive:
        src: /opt/apache-tomcat-9.0.79.tar.gz
        dest: /opt
        remote_src: yes
    - name: providing permission
      file:
        path: /opt/apache-tomcat-9.0.79/bin/startup.sh
        mode: 0777
    - name: start tomcat service
      shell: nohup ./startup.sh
      args:
        chdir: /opt/apache-tomcat-9.0.79/bin
    - name: Clone and  Pull the Git repository
      git:
        repo: https://github.com/saikumartanakala/project1.git
        dest: /root/gitnew
        version: main
        update: yes
    - name: buildin maven
      shell: mvn -f /root/gitnew/pom.xml clean
    - name: permission
      file:
        path: /root/gitnew/
        mode: 0777
    - name: download a war file
      get_url:
        url: https://raw.githubusercontent.com/aeimer/java-example-helloworld-war/master/dist/helloworld.war
        dest: /opt/apache-tomcat-9.0.79/webapps/new.war
