---
- hosts: all
  tasks:
    - name: create multiple files
      file:
        path: "{{item}}"
        state: touch
      loop:
        - /root/file1
        - /root/file2
        - /root/file3
      
