---
- hosts: all
  user: root
  tasks:
    - name: Download Tomcat tar.gz
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.79/bin/apache-tomcat-9.0.79.tar.gz
        dest: /tmp/apache-tomcat.tar.gz

    - name: Create Tomcat Directory
      file:
        path: /opt/tomcat
        state: directory

    - name: Extract Tomcat Archive
      unarchive:
        src: /tmp/apache-tomcat.tar.gz
        dest: /opt/tomcat
        remote_src: yes

    - name: Change Tomcat Permissions
      file:
        path: /opt/tomcat
        mode: 0777

    - name: Start Tomcat Service
      shell: nohup./startup.sh
      args:
        chdir: /opt/apache-tomcat-9.0.79/bin
      









