---
- hosts: all
  user: root
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: present
    - name: start httpd
      service:
        name: httpd
        state: started
    - name: deploy index.html
      copy:
        src: /root/index.html
        dest: /var/www/html/index.html
