---
- name: Install Tomcat
  hosts: all
  user: root
  tasks:
    - name: Install OpenJDK
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Install Tomcat
      apt:
        name: tomcat9
        state: present

    - name: Start Tomcat service
      shell: nohup./startup.sh
      args:
        chdir: /opt/apache-tomcat-9.0.79/bin


